### ISSUE TITLE
编译环境设置

### ISSUE THREAD

**Issue by shuyulei0130** [houluy/bupTemplate#1]
你好，学长，能够发一下编译环境的设置问题，我在macos的vscode下面好像无法编译

**Comment by houluy** [comment]
你的latex编译器的版本是什么呢？

**Comment by DaftDogeee** [comment]
`TeXLive 2017`之后的版本 + `xelatex`编译即可。注意：所有`tex`文件必须是`UTF8`编码！

另外如果使用`bibtex`，需要进行多次编译，一般的顺序是
`xelatex main.tex`
`bibtex main.tex`
`xelatex main.tex`
`xelatex main.tex`

因此，建议使用`TeXStudio`进行一键编译（当然，自己写一个脚本也是可以的），这是一个跨`Windows`、`MacOS`、`Linux`三平台的软件。

**Comment by shuyulei0130** [comment]
万分感谢~
